第4回課題提出です
nozomi2303/RaiseTech pull request #2
Opened 2023-05-14 20:34 UTC by nozomi2303

ご確認お願い致します！

2023-05-15 01:32 UTC, tomo989-h requested changes
提出ありがとうございます！
エビデンスとしてEC2とRDS連携と接続の部分しかないのですが、他にもVPCを作成したりEC2を作成したりRDSを作成したりセキュリティグループを作成したりなどの作業をしていると思います！
そのエビデンスもこのファイルの中に含めてください 🙏

2023-05-15 01:32 UTC, tomo989-h commented on learn04.md
> +![image](img width="683" alt="rds-ec2-2" src="https://github.com/nozomi2303/RaiseTech/assets/129904330/f78a5a6a-0d21-4631-b041-e9f0a2e078f3")
ここ、画像がうまく表示されていないので確認をお願いします！
Githubに直接画像をアップロードされてますかね？
その方法ではなく、リポジトリ自体に画像をあげていただき、相対参照をして画像を表示させるようにしていただきたいです。
そうしないと画像の変更履歴が残らないので。

2023-05-15 01:32 UTC, tomo989-h commented on learn04.md
> +
こちらも上と同じ指摘となります

2023-05-16 22:01 UTC, nozomi2303 commented
修正致しましたのでご確認宜しくお願い致します。

2023-05-17 00:55 UTC, tomo989-h requested changes
コメントしておりますので確認をお願いします 🙏

2023-05-17 00:55 UTC, tomo989-h commented on learn04.md
> +![vpc-security](img src="images/rt-vpc-security.png")
うまく表示できてないですね。。。
再度、GithubでのMarkdownで画像を参照する書き方を調べてみてください 🙏 
書き方が間違っていると思います！

2023-05-17 00:55 UTC, tomo989-h commented on learn04.md
> +![ec2](img src="images/rt-ec2.png")
こちらも上と同じ指摘です。

2023-05-17 00:55 UTC, tomo989-h commented on learn04.md
> +![rds-ec2](img src="images/rds-ec2-2.png")
こちらも上と同じ指摘です。

2023-05-17 00:55 UTC, tomo989-h commented on learn04.md
> +![ec2-rds](img src="images/ec2rdsconnect.png")
こちらも上と同じ指摘です。

2023-05-17 20:10 UTC, nozomi2303 commented
修正いたしました！

2023-05-17 23:31 UTC, tomo989-h requested changes
画像の表示OKです！
気になったところをコメントしておりますので確認をお願いします 🙏

2023-05-17 23:31 UTC, tomo989-h commented on learn04.md
> +![vpc-security](images/rt-vpc-security.png)
セキュリティグループはEC2とRDSで同じものを使っていますかね？
基本、セキュリティグループは必要最低限の通信を開けるが基本になります
EC2もRDSも必要なセキュリティグループの設定は違いますよね？
そのため、分けていただいて方がいいですよ！

また、今回送信元をIPアドレスで設定していますね。
実はIPアドレス以外でも設定が可能です。
少し調べてくると出てくると思うので調べてみて、今回はどの設定がいいか吟味してみてください。

2023-05-17 23:31 UTC, tomo989-h commented on learn04.md
> +![rds](images/rt-rds.png)
サブネットグループに4つのサブネットが登録されています。
今の状態だと不都合が起きてしまうんですが、一度サブネットグループがどいういものか調べてみてください 🙏

2023-05-20 08:11 UTC, nozomi2303 commented
RDSを再作成、セキュリティグループ、サブネットグループの変更を致しました。
EC2から再作成したRDSヘの接続確認もしております。
ご確認の程宜しくお願い致します。

2023-05-20 08:26 UTC, tomo989-h approved these changes
修正ありがとうございます！
課題はOKです！
今回は色々考えたことがあると思います。
それはちゃんと自分の力になると思うので次の課題も頑張ってください 🙏 

最後1点だけコメントしております。
こちら確認していただいてマージしてください！

2023-05-20 08:26 UTC, tomo989-h commented on learn04.md
> +![ec2-security](images/ec2-security-0520.png)
1つコメントだけ 🙏 
22番ポートを0.0.0.0/0で設定しているのってかなり危ないです。
この状況ってログインする経路は誰でもアクセスできるよという状況です
この設定をやっていたことでサーバーの乗っ取りや認証情報を奪われて高額なAWS利用料金の請求がきてしまったとかよくあります。
お時間あるときで大丈夫なので自分のPCからしか接続できないようIPアドレスを絞ることは検討してみてください。

2023-05-20 08:36 UTC, tomo989-h approved these changes
Approveしてなかったですね！ごめんなさい！

2023-05-20 19:38 UTC, nozomi2303 commented
ご確認ありがとうございました！
22番ポートのIPアドレスは早急に修正致します！

2023-05-20 19:38 UTC, merged