第10回課題提出致します。
nozomi2303/RaiseTech pull request #9
Opened 2023-09-14 20:25 UTC by nozomi2303

ご確認の程宜しくお願い致します！

2023-09-15 04:34 UTC, MasatoshiMizumoto requested changes
拝見しました！
課題条件は満たしていますがコードで気になったところを書いてます！
最低限typoは直していただければ！

2023-09-15 04:34 UTC, MasatoshiMizumoto commented on learn10-cfn.yml
> +  PBSubnetcider01:
cider -> CIDRが一般的ですね！
```suggestion
  PBSubnetCIDR01:
```

2023-09-15 04:34 UTC, MasatoshiMizumoto commented on learn10-cfn.yml
> +       - "m1.large"
特段限定する意図がないなら入れなくても良いかなと思いました！

2023-09-15 04:34 UTC, MasatoshiMizumoto commented on learn10-cfn.yml
> +    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
これは賛否分かれるんですが、この書き方って戻り値が変動するので、運用するとスタックに差分（drift）が発生して好ましくないですねー。
EC2ってAMIのID変わったら作り直しな（サーバー消えちゃう）ので、それがシステム運用にとって良いかどうかは考えてもらったら見えるかなと！

2023-09-15 04:34 UTC, MasatoshiMizumoto commented on learn10-cfn.yml
> +    Type: 'AWS::EC2::KeyPair::KeyName'
キーはCFnでも作れるので、今後やってみてください！

2023-09-15 04:34 UTC, MasatoshiMizumoto commented on learn10-cfn.yml
> +    Description: MyS3Bucketforlearn10
末尾に改行がないとGitHubのレビューで指摘が来るので、ここ確認してみてください！
VSCodeの設定で防げます！

2023-09-15 20:36 UTC, nozomi2303 commented on learn10-cfn.yml
> +  PBSubnetcider01:
大変失礼致しました！
こちら修正致しました！

2023-09-15 20:37 UTC, nozomi2303 commented on learn10-cfn.yml
> +       - "m1.large"
こちら削除致しました！
実務ではこのようにした方がいいのかな？と思って入れてみた感じでした！

2023-09-15 20:40 UTC, nozomi2303 commented on learn10-cfn.yml
> +    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
そうなのですね、教えて頂きありがとうございます！
AMIIDは割と高頻度で変更されてしまうので、自動で最新のAMIIDを選択してくれるのならその方がいいのだと思っていました。
ただAMIID変更で消えてしまうのは問題ですね…。この点で賛否両論分かれる、って感じでしょうか。
こちらはDefaultで現時点での最新のAMIID固定にしました。

2023-09-15 20:42 UTC, nozomi2303 commented on learn10-cfn.yml
> +    Type: 'AWS::EC2::KeyPair::KeyName'
かしこまりました！
今後はそのように致します！

2023-09-15 20:42 UTC, nozomi2303 commented on learn10-cfn.yml
> +    Description: MyS3Bucketforlearn10
VSCodeの設定変更致しました！

2023-09-15 20:44 UTC, nozomi2303 commented
修正してアップ致しました！
ご確認の程宜しくお願い致します。

2023-09-16 03:31 UTC, MasatoshiMizumoto approved these changes
LGTM!
![LGTM](https://image.lgtmoon.dev/161206)

2023-09-16 19:50 UTC, nozomi2303 commented
ご確認ありがとうございました！

2023-09-16 19:51 UTC, merged